GET http://localhost:4000/tutors

###


# get one by ID

GET http://localhost:4000/tutors/621364861

###POST ONE

POST http://localhost:4000/auth/login-tutor
Content-Type: application/json

{
  "username": "HopeB",
  "password": "123"

}

###DELETE BY ID

DELETE http://localhost:4000/tutors/622b15b70d2daa97f3fcd57f



###UPDATE BY ID

PATCH http://localhost:4000/tutors
Content-Type: application/json

{
  "fullname":"Lee Bernad",
  "subject": "Mathematics ",
  "password": "123"
  
}


