GET http://localhost:4000/tutors

###


# get one by ID

GET http://localhost:4000/tutors/find/6231e5afd5e9401d2886a4d6



###POST ONE ( Register user)
POST http://localhost:4000/auth/register-tutor
Content-Type: application/json

{
  "fullname": "Lana Mzi",
  "username": "LanaM",
  "grades": "12",
    "subject": "maths",
      "location": "Langa"


}

### Login- tutor


POST http://localhost:4000/auth/login-tutor
Content-Type: application/json

{
  "username": "BenF",
  "password": "123"

}

###DELETE BY ID

DELETE http://localhost:4000/tutors/6232f029eb4ac1b49a6c2ebf



###UPDATE BY ID

PUT http://localhost:4000/tutors
Content-Type: application/json

{
  "fullname":"Lee Bernad",
  "subject": "Mathematics ",
  "password": "123"
  
}

# --------------------------------------S T U D E N T S-----------------------------------------------------------------------#
#####

GET http://localhost:4000/students

###


# get one by ID

GET http://localhost:4000/students/find/623b060ec19cf9cff1aaf445



###POST ONE
POST http://localhost:4000/auth2/register-student
Content-Type: application/json

{
  "fullname": "Name1 A1 ",
  "username": "Name1A",
  "password": "123"
}

### login-student


POST http://localhost:4000/auth2/login-student
Content-Type: application/json

{
"username": "Saun",
  "password": "123"

}

###DELETE BY ID

DELETE http://localhost:4000/students/623b060ec19cf9cff1aaf445



###UPDATE BY ID

PUT http://localhost:4000/students/62343666c14229326e3118d2
Content-Type: application/json

{
  "fullname":"Saun Carter",
  "username": "Saun",
  "password": "123"
  
}

