GET http://localhost:4000/tutors

###

GET http://localhost:4000/tutors/621364861

###

POST http://localhost:4000/tutors
Content-Type: application/json

{
  "name":"Maze Person",
  "registeredToPlatform": "Thuto "  
}

###

DELETE http://localhost:4000/tutors/6213828511f85262499c865a

###

PATCH http://localhost:4000/tutors/6213711911f85262499c864f
Content-Type: application/json

{
    "name":"Bronn Donald"
}


